# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/IndentationWidth:
  Width: 2
  Enabled: true

Layout/LineLength:
  Max: 100
  Enabled: true
